import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const pageSource = readFileSync(join(__dirname, "page.tsx"), "utf8");
const releaseActionsSource = readFileSync(join(__dirname, "release-notes-actions.tsx"), "utf8");
const exportRouteSource = readFileSync(join(__dirname, "export", "route.ts"), "utf8");
const historyExportRouteSource = readFileSync(join(__dirname, "release-history", "export", "route.ts"), "utf8");

describe("platform feedback version filter wiring", () => {
  it("keeps appVersion in page filter links and export route parsing", () => {
    expect(pageSource).toContain("appVersion");
    expect(pageSource).toContain("Version");
    expect(pageSource).toContain("currentAppMetadata.version");
    expect(pageSource).toContain("Release triage");
    expect(pageSource).toContain("inbox.releaseTriage");
    expect(pageSource).toContain("Release notes draft");
    expect(pageSource).toContain("inbox.releaseNotesDrafts");
    expect(pageSource).toContain("Release workflow");
    expect(pageSource).toContain("inbox.releaseWorkflows");
    expect(pageSource).toContain("Release readiness");
    expect(pageSource).toContain("inbox.releaseReadiness");
    expect(pageSource).toContain("Release history");
    expect(pageSource).toContain("inbox.releaseHistory");
    expect(pageSource).toContain("inbox.releaseHistorySummary");
    expect(pageSource).toContain("Planning events");
    expect(pageSource).toContain("Planning actors");
    expect(pageSource).toContain("actorCounts");
    expect(pageSource).toContain("Top planning actor");
    expect(pageSource).toContain("topActor");
    expect(pageSource).toContain("No actor yet");
    expect(pageSource).toContain("No actor events yet");
    expect(pageSource).toContain("Use Plan release items to create the first release history event.");
    expect(pageSource).toContain("Release history and CSV export follow the selected version filter.");
    expect(pageSource).toContain("History scope");
    expect(pageSource).toContain("releaseHistoryScope");
    expect(pageSource).toContain("View all history");
    expect(pageSource).toContain("appVersion: undefined");
    expect(pageSource).toContain("Current version history");
    expect(pageSource).toContain("appVersion: currentAppMetadata.version");
    expect(pageSource).toContain("/platform/feedback/release-history/export");
    expect(pageSource).toContain("releaseHistoryExportParams");
    expect(pageSource).toContain("filters.appVersion");
    expect(pageSource).toContain("Download Markdown");
    expect(pageSource).toContain("ReleaseNotesActions");
    expect(pageSource).toContain("/platform/feedback/release-notes/export");
    expect(releaseActionsSource).toContain("Plan release items");
    expect(releaseActionsSource).toContain("planReleaseFeedbackAction");
    expect(releaseActionsSource).toContain("actorUserId");
    expect(releaseActionsSource).toContain("router.refresh");
    expect(exportRouteSource).toContain("appVersion: url.searchParams.get(\"appVersion\")");
    expect(historyExportRouteSource).toContain("exportPlatformReleaseHistoryCsvAction");
    expect(historyExportRouteSource).toContain("appVersion: url.searchParams.get(\"appVersion\")");
    expect(historyExportRouteSource).toContain("text/csv; charset=utf-8");
  });
});
